[plugin]
repository = "https://github.com/una-xiv/umbra.git"
commit = "968c8b0d90886214875108f993ac0189c78a2fe4"
owners = [
    "haroldiedema",
    "alexpado",
    "Bloodsoul",
    "MeowZWR"
]
project_path = "Umbra"
