[plugin]
repository = "https://github.com/una-xiv/umbra.git"
commit = "88f997f27e48a20d358016e2bc7c00e0084df2ba"
owners = [
    "haroldiedema",
    "alexpado",
    "Bloodsoul",
    "MeowZWR"
]
project_path = "Umbra"
