[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "42d1c862dca41ddaacb59dcdf7ef692fd18679c1"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "修复招募" 
