[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "b01986dff9e7c268b7d3c6a3bc45787b25e79a21"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "修复招募" 
