[plugin]
repository = "https://github.com/Infiziert90/ChatTwo.git"
commit = "4b62530cd640d15904fe622f9e7e17f640d0ab64"
owners = [
    "Infiziert90",
    "lojewalo",
    "MeowZWR"
]
project_path = "ChatTwo"
