[plugin]
repository = "https://github.com/Infiziert90/ChatTwo.git"
commit = "1862410402468509f05c973e019f38835aa3a5a7"
owners = [
    "Infiziert90",
    "lojewalo",
    "MeowZWR"
]
project_path = "ChatTwo"
