[plugin]
repository = 'https://github.com/MapleRecall/OrangeGuidanceTomestone.git'
commit = 'd36961cf491bbf3d21df875f6fc4ef7f24e8f86f'
owners = [ 'anna-is-cute', 'MapleRecall' ]
project_path = 'client'
changelog = """\
- 简单汉化一下？
"""
