[plugin]
repository = "https://github.com/Styr1x/Browsingway.git"
commit = "d7812128161989b7633bd0de6052b92db9f7217a"
owners = ["Styr1x", "MeowZWR"]
project_path = "Browsingway"
changelog = """\
- Bump Chromium to 143.0.7499.40
- Api 14
"""
