[plugin]
repository = "https://github.com/Styr1x/Browsingway.git"
commit = "fd2cfff55d6d0e17328063302124e8f95cf82890"
owners = ["Styr1x", "MeowZWR"]
project_path = "Browsingway"
changelog = """\
- Bump Chromium to 143.0.7499.40
- Api 14
"""
