[plugin]
# The open-source Git repository that your code is hosted on.
# Must be visible to the external web, but doesn't have to be GitHub.
# If `git clone` accepts it, it will work here, with the caveat that it
# must be accessible (i.e. no `git` or `ssh` URLs, as the agent cannot clone those)
repository = "https://github.com/Loskh/DcTraveler.git"
# The commit to check out and build from the repository.
commit = "630287165982949d37bc3acef1b4263ff9a03f93"
# The people authorised to update this manifest (e.g. who can deploy updates). These are GitHub usernames.
owners = [
    "Loskh"
]
changelog = '''原生，启动！'''


