[plugin]
# The open-source Git repository that your code is hosted on.
# Must be visible to the external web, but doesn't have to be GitHub.
# If `git clone` accepts it, it will work here, with the caveat that it
# must be accessible (i.e. no `git` or `ssh` URLs, as the agent cannot clone those)
repository = "https://github.com/Loskh/DcTraveler.git"
# The commit to check out and build from the repository.
commit = "0e1d65d49a561b87cd7cf02ac4b2592cf612352c"
# The people authorised to update this manifest (e.g. who can deploy updates). These are GitHub usernames.
owners = [
    "Loskh"
]
changelog = '''解除火爆大区(指鸟区)传送限制,原来手机叨鱼可以跨,只有网页不行'''


