[plugin]
repository = "https://github.com/DutyPusher/FFXIVDutyPusher.git"
commit = "887852ef3257d0b7c10f309cd3fff33c956fbe88"
owners = ["MorCherlf"]
project_path = "DutyPusher"
changelog = """\
Update Chinese
"""