[plugin]
repository = "https://github.com/DutyPusher/FFXIVDutyPusher.git"
commit = "ab43c3c65874998cf222e82541ae310c42a4ee54"
owners = ["MorCherlf"]
project_path = "DutyPusher"
changelog = """\
Update Chinese Description
"""