[plugin]
# The open-source Git repository that your code is hosted on.
# Must be visible to the external web, but doesn't have to be GitHub.
# If `git clone` accepts it, it will work here, with the caveat that it
# must be accessible (i.e. no `git` or `ssh` URLs, as the agent cannot clone those)
repository = "https://github.com/wozaiha/DalamudACT.git"
# The commit to check out and build from the repository.
commit = "b67361f610e3bd60ac508a777ff4877754dd9b29"
# The people authorised to update this manifest (e.g. who can deploy updates). These are GitHub usernames.
owners = [
    "wozaiha"
]
changelog = '''
- 测试测试测试'''


