[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "766faea18891b0c4197ec7a57f4563f6331df600"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "修复招募" 
