[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "e8673570dd2f356c921c2b9f93f6b8f23dd42cf2"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "Update API XIV" 
