[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "b2280369078075bbd077dc32cd41885229324a98"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "由于收到一些导致招募崩溃的反馈，招募反屏蔽已暂时关闭。" 
