[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "ee6cd3ac969d4b9648efb88e100e8b8eedcc828b"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "暂时禁用招募" 
