[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "7588c5f8bf64656451dff77fa91fb229df2be3ba"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "重构逻辑，当存在某些无法发出的招募文本时，行为和原生游戏一致，不会出现没开插件的玩家看到空白招募的情况。" 
