[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "2d5cd9e193855f4b938b1f19655ff5e9c35e949a"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "修复招募" 
