[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "7b986c943f53bbacd097895139ac77d37bcde55d"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "暂时禁用招募" 
