[plugin]
repository = 'https://github.com/LittleNightmare/remote-party-finder.git'
commit = '83074027315e6cf38128f06edd2af3ddf185331e'
owners = [ 'LittleNightmare' ]
project_path = 'csharp/RemotePartyFinder'
changelog = 'Update for 7.4'
