[plugin]
repository = 'https://github.com/LittleNightmare/remote-party-finder.git'
commit = '988049f7e4fc36af3f1811cb72a9b3645bfa5276'
owners = [ 'LittleNightmare' ]
project_path = 'csharp/RemotePartyFinder'
changelog = 'Update for 7.4'
