[plugin]
repository = "https://github.com/ottercorp/MarketBoardPlugin.git"
commit = "5be02b8100a5089c6c75216cce8176be3501916f"
owners = ["fmauNeko", "Yarukon"]
project_path = "MarketBoardPlugin"
changelog = """
- Fix server check
"""
