[plugin]
repository = "https://github.com/ottercorp/MarketBoardPlugin.git"
commit = "c1d93f0ddfcc87b493d78a08d60a0505fa27349a"
owners = ["fmauNeko", "Yarukon"]
project_path = "MarketBoardPlugin"
changelog = """
- Patch 7.4 / API 14 compatibility
- Allow including Oceania in Cross-DC searches (added a checkbox in settings)
- Added support for China Cross-DC
"""
