[plugin]
repository = "https://github.com/MapleRecall/VanillaPlus.git"
commit = "7e8a3f591556dbbe826829b0c851668a8b9545da"
owners = ["MidoriKami", "Haselnussbomber", "MapleRecall"]
project_path = "VanillaPlus"
